version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command

workflows:
  sch1:
    when:
      not:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - hello-job

  sch2:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ minutely, << pipeline.schedule.name >> ]
    jobs:
      - hello-job